# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lingua-Zompist-Cuezi
version:      0.01
version_from: Cuezi.pm
installdirs:  site
requires:
    Test::More:                    0.19

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
